### ISSUE TITLE
Anteproyecto-Equipo 4

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-4#1]
[Anteproyecto.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-4/files/9701060/Anteproyecto.pdf)

**Comment by AmeliReyesHernandez** [comment]
18

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
